const getEndPoint = <T extends Record<string, string>>(
  baseURL: string,
  subEndpoint: T
) => {
  for (const key in subEndpoint) {
    subEndpoint[key] = `/${baseURL}/${subEndpoint[key]}` as T[Extract<
      keyof T,
      string
    >];
  }

  return subEndpoint;
};

export const endpoints = getEndPoint("api/v1", {
  ME: "auth/me",
  LOGIN: "auth/login",
  LOGOUT: "auth/logout",
  REFRESH: "auth/refresh",
  ROLE: "role",
  USERS: "users",
  DASHBOARD_SUMMARY: "dashboard/summary",
  DASHBOARD_RECENT_ACTIVITIES: "dashboard/recent-activities",
  DASHBOARD_MODULE_STATS: "dashboard/module-stats",
  DASHBOARD_STATUS_CHART: "dashboard/status-chart",

  LOCATIONS: "locations",
  RBAC_ROLES: "rbac/roles",
  RBAC_PERMISSIONS: "rbac/permissions",
  ASSET_GROUPS: "asset-groups",
  CATALOG_TYPES: "catalog-types",
  CATALOG_GROUPS: "catalog-groups/",
  STATUSES: "statuses",
  USAGE_MODES: "usagemodes",
  SUPPLIERS: "suppliers",
  CUSTOMERS: "customers",
  PHYSICAL_ASSETS: "physical-assets",
  PHYSICAL_ASSETS_EXPORT_EXCEL: "physical-assets/export/excel",
  PHYSICAL_ASSETS_IMPORT_EXCEL: "physical-assets/import/excel",
  UNITS: "units/",
  ORG_UNITS: "org",
  UPLOAD_ATTACHMENTS: "attachments/upload//",
  STOCKS: "stocks/",
  RENTALS: "rentals",
  ALLOCATIONS: "allocations/",
  RECOVERIES: "recoveries/",
  STAFFS: "staffs",
  TEMPLATES: "workflows/templates",
  TEMPLATE_ACTIVE: "workflows/templates/active/",
  TRANSFERS: "transfers",
  WORKFLOW_TASKS: "workflows/tasks/",
  STOCK_ADJUSTMENTS: "stock-adjustments",
  AUDIT_MY_AUDITS: "audit/my-audits",
  AUDIT_PENDING_APPROVAL: "audit/pending-approval",
  AUDIT_SESSIONS: "audit/sessions",
  AUDIT_BATCH_START: "audit/batch-start",
  TREE: 'tree',
  MAINTENANCES: "maintenances",
  LIQUIDATIONS: "liquidations",
  OFFICES: "offices",
  IMPORTANCES: "asset-classifications/importances",
  LOGS: "logs",
});

export const dynamicEndpoints = {
  USER_DETAIL: (id: number) => `/api/v1/users/${id}`,
  USER_CHANGE_PASSWORD: (id: number) => `/api/v1/users/${id}/change-password`,
  USER_RESET_PASSWORD: (id: number) => `/api/v1/users/${id}/reset-password`,
  RBAC_ROLE_DETAIL: (id: number) => `/api/v1/rbac/roles/${id}`,
  LOCATION_DETAIL: (id: number) => `/api/v1/locations/${id}`,
  ASSET_GROUP_DETAIL: (id: number) => `/api/v1/asset-groups/${id}`,
  CATALOG_TYPE_DETAIL: (id: number) => `/api/v1/catalog-types/${id}`,
  STATUS_DETAIL: (id: number) => `/api/v1/statuses/${id}`,
  USAGE_MODE_DETAIL: (id: number) => `/api/v1/usagemodes/${id}`,
  SUPPLIER_DETAIL: (id: number) => `/api/v1/suppliers/${id}`,
  CUSTOMER_DETAIL: (id: number) => `/api/v1/customers/${id}`,
  ORG_UNIT_DETAIL: (id: number) => `/api/v1/org/${id}`,
  TEMPLATE_DETAIL: (id: number) => `/api/v1/workflows/templates/${id}`,
  PHYSICAL_ASSET_DETAIL: (id: number) => `/api/v1/physical-assets/${id}`,
  PHYSICAL_ASSET_HOLDERS: (id: number) => `/api/v1/physical-assets/${id}/holders`,
  PHYSICAL_ASSET_STOCK: (id: number) => `/api/v1/physical-assets/${id}/stock`,
  PHYSICAL_ASSET_MODULES: (id: number) => `/api/v1/physical-assets/${id}/modules`,
  PHYSICAL_ASSET_CLONE: (id: number) => `/api/v1/physical-assets/${id}/clone`,
  PHYSICAL_ASSET_MODULES_DETAIL: (asset_id: number, module_id: number) => `/api/v1/physical-assets/${asset_id}/modules/${module_id}`,
  RENTAL_DETAIL: (id: number) => `/api/v1/rentals/${id}`,
  RENTAL_RETURN: (id: number) => `/api/v1/rentals/${id}/return`,
  RENTAL_RENEW: (id: number) => `/api/v1/rentals/${id}/renew`,
  STAFF_DETAIL: (id: number) => `/api/v1/staffs/${id}`,
  STAFF_CREATE_USER: (id: number) => `/api/v1/staffs/${id}/create-user`,
  TRANSFER_DETAIL: (id: number) => `/api/v1/transfers/${id}`,
  TRANSFER_ATTACHMENTS: (id: number) => `/api/v1/transfers/${id}/attachments`,
  WORKFLOW_TASK_COMPLETE: (id: number) => `/api/v1/workflows/tasks/${id}/complete`,
  AUDIT_COMPLETE: (id: number) => `/api/v1/audit/${id}/complete`,
  AUDIT_SESSION_DETAIL: (id: number) => `/api/v1/audit/sessions/${id}`,
  AUDIT_SESSION_DETAILS: (id: number) => `/api/v1/audit/${id}/details`,
  AUDIT_APPROVE: (id: number) => `/api/v1/audit/${id}/approve`,
  AUDIT_REJECT: (id: number, reason: string) =>
    `/api/v1/audit/${id}/reject?reason=${encodeURIComponent(reason)}`,
  ALL_LOCATION_DETAIL: (id: number) => `/api/v1/allocations/${id}`,
  PHYSICAL_ASSET_LIFECYCLE: (id: number) => `/api/v1/physical-assets/${id}/lifecycle`,
  WORKFLOW_HISTORY: (type: string, id: number) => `/api/v1/workflows/history/${type}/${id}`,
  STOCK_ADJUSTMENT_DETAIL: (id: number) => `/api/v1/stock-adjustments/${id}`,
  MAINTENANCE_DETAIL: (id: number) => `/api/v1/maintenances/${id}`,
  LIQUIDATION_DETAIL: (id: number) => `/api/v1/liquidations/${id}`,
  OFFICE_DETAIL: (id: number) => `/api/v1/offices/${id}`,
  DOCUMENT_DETAIL: (documentType: string, id: number) => {
    const map: Record<string, string> = {
      allocation: `/api/v1/allocations/${id}`,
      stock_in: `/api/v1/stock-adjustments/${id}`,
      stock_out: `/api/v1/stock-adjustments/${id}`,
      transfer: `/api/v1/transfers/${id}`,
      recovery: `/api/v1/recoveries/${id}`,
      rental: `/api/v1/rentals/${id}`,
      liquidation: `/api/v1/liquidations/${id}`,
      maintenance: `/api/v1/maintenances/${id}`,
      rental_return: `/api/v1/rentals/returns/${id}`,
    };
    return map[documentType] ?? `/api/v1/allocations/${id}`;
  },
  UPLOAD_ATTACHMENTS: (documentType: string, id: number) => `/api/v1/${documentType}/${id}/attachments`,
  AUDIT_DETAIL_UPDATE: (id: number) => `/api/v1/audit/details/${id}`,
  SCAN_INFO: (code: string) => `/api/v1/scan/${encodeURIComponent(code)}/info`,
};